window.SITE_CONFIG = {
  companyName: 'PrimeFlow Plumbing',
  shortName: 'PrimeFlow',
  tagline: 'Premium Plumbing Solutions for Northeastern Pennsylvania',
  description: 'Licensed and insured plumbing contractor serving NEPA. Residential, commercial, emergency plumbing, drain cleaning, water heaters, and full-service plumbing solutions.',
  phone: '(570) 000-0000',
  phoneRaw: '5700000000',
  email: 'info@primeflowplumbing.com',
  address: 'Northeastern Pennsylvania',
  hours: 'Mon–Fri: 7AM–6PM | Sat: 8AM–2PM | Sun: Emergency Only',
  license: 'Licensed & Insured',
  yearFounded: '2020',
  domain: 'primeflowplumbing.com',

  social: {
    facebook: '#',
    instagram: '#',
    google: '#',
    yelp: '#',
  },

  navigation: [
    { id: 'home', label: 'Home', url: '/' },
    { id: 'about', label: 'About', url: '/about' },
    { id: 'services', label: 'Services', url: '/services', hasDropdown: true },
    { id: 'service-areas', label: 'Service Areas', url: '/service-areas', hasDropdown: true },
    { id: 'gallery', label: 'Gallery', url: '/gallery' },
    { id: 'testimonials', label: 'Reviews', url: '/testimonials' },
    { id: 'blog', label: 'Blog', url: '/blog' },
    { id: 'contact', label: 'Contact', url: '/contact' },
  ],

  secondaryNav: [
    { label: 'FAQ', url: '/faq' },
    { label: 'Financing', url: '/financing' },
    { label: 'Coupons', url: '/coupons' },
    { label: 'Emergency', url: '/services/emergency-plumbing' },
  ],

  services: [
    {
      id: 'emergency-plumbing',
      title: 'Emergency Plumbing',
      icon: 'emergency',
      category: 'emergency',
      shortDesc: 'Burst pipes, major leaks, or sewage backups — our emergency plumbers respond fast, 24/7, to protect your home from water damage.',
      description: 'When a plumbing emergency strikes, every minute counts. PrimeFlow Plumbing provides rapid 24/7 emergency plumbing services across Northeastern Pennsylvania. Whether you\'re dealing with burst pipes, severe leaks, sewage backups, or a complete loss of water, our licensed plumbers arrive quickly with fully stocked trucks to resolve your crisis. We understand the stress and urgency of plumbing emergencies, which is why we prioritize fast response times and immediate solutions to minimize damage to your property.',
      processSteps: ['Call our 24/7 emergency line', 'Technician dispatched immediately', 'Rapid diagnosis and containment', 'Emergency repair completed'],
      benefits: ['24/7 availability — nights, weekends, holidays', 'Average 60-minute response time', 'Fully stocked service vehicles', 'Upfront emergency pricing — no surprise fees', 'Licensed and insured technicians', 'Water damage mitigation included'],
      commonProblems: ['Burst or frozen pipes', 'Sewage backup into home', 'Major water leaks', 'No hot water in winter', 'Overflowing toilets', 'Gas line leaks', 'Sump pump failure during storms'],
      faqs: [
        { q: 'How fast can you respond to an emergency?', a: 'We aim for a 60-minute response time across our NEPA service area. Our dispatchers prioritize emergencies and send the nearest available technician.' },
        { q: 'Do you charge extra for nights and weekends?', a: 'We provide upfront pricing before any work begins. While emergency rates may differ from standard rates, there are never hidden fees or surprise charges.' },
        { q: 'What should I do while waiting for the plumber?', a: 'Shut off the main water valve if possible, turn off the water heater, and move valuables away from the affected area. Our dispatcher will guide you through these steps on the phone.' },
      ],
      relatedServices: ['leak-detection', 'pipe-repair', 'sump-pump-repair', 'frozen-pipe-repair'],
    },
    {
      id: 'drain-cleaning',
      title: 'Drain Cleaning',
      icon: 'drain',
      category: 'drains',
      shortDesc: 'Professional drain cleaning for slow, clogged, or backed-up drains. We restore full flow to sinks, tubs, showers, and main sewer lines.',
      description: 'Slow or clogged drains are more than an inconvenience — they can lead to sewage backups, water damage, and health hazards. PrimeFlow Plumbing uses professional-grade drain cleaning equipment including motorized augers and hydro jetting to clear even the most stubborn blockages. From kitchen sink grease buildup to tree root intrusion in main sewer lines, our experienced technicians diagnose the root cause and provide lasting solutions, not temporary fixes.',
      processSteps: ['Video inspection to locate blockage', 'Select optimal clearing method', 'Professional drain cleaning', 'Flow verification and prevention tips'],
      benefits: ['Same-day service available', 'Video camera inspection included', 'Multiple clearing methods available', 'Preventive maintenance plans', 'Safe for all pipe types', 'Written guarantee on all work'],
      commonProblems: ['Slow-draining sinks or tubs', 'Recurring kitchen drain clogs', 'Bathroom drain hair buildup', 'Main sewer line blockages', 'Floor drain backups', 'Tree root intrusion', 'Grease-clogged restaurant drains'],
      faqs: [
        { q: 'How often should I have my drains professionally cleaned?', a: 'We recommend annual drain cleaning for most homes. Kitchens with heavy use or older homes with cast iron pipes may benefit from semi-annual service.' },
        { q: 'Are chemical drain cleaners safe to use?', a: 'We strongly advise against chemical drain cleaners. They can damage pipes, harm the environment, and often only provide temporary relief. Professional cleaning is safer and more effective.' },
        { q: 'Do you clean main sewer lines?', a: 'Absolutely. We handle everything from individual fixture drains to main sewer line cleaning using hydro jetting and specialized equipment.' },
      ],
      relatedServices: ['hydro-jetting', 'sewer-line-repair', 'kitchen-plumbing', 'bathroom-plumbing'],
    },
    {
      id: 'water-heater-repair',
      title: 'Water Heater Repair',
      icon: 'waterHeater',
      category: 'water-heaters',
      shortDesc: 'Expert water heater repair for all brands and types. We restore your hot water fast with same-day service available.',
      description: 'A malfunctioning water heater can disrupt your entire household. PrimeFlow Plumbing provides expert water heater repair for all major brands including Rheem, Bradford White, AO Smith, and more. Whether your unit produces no hot water, makes strange noises, leaks, or delivers inconsistent temperatures, our technicians diagnose the issue quickly and carry common replacement parts on our trucks for same-day repairs. We service both tank and tankless water heaters.',
      processSteps: ['Thorough diagnostic assessment', 'Upfront repair quote provided', 'Professional repair with quality parts', 'System test and performance verification'],
      benefits: ['All major brands serviced', 'Same-day repair available', 'Parts carried on service trucks', 'Tank and tankless expertise', 'Energy efficiency assessment', 'Honest repair-vs-replace advice'],
      commonProblems: ['No hot water', 'Inconsistent water temperature', 'Strange noises from tank', 'Water heater leaking', 'Pilot light won\'t stay lit', 'Rusty or discolored hot water', 'High energy bills from inefficient unit'],
      faqs: [
        { q: 'How long do water heaters typically last?', a: 'Traditional tank water heaters last 8-12 years, while tankless units can last 15-20 years with proper maintenance. We can assess your unit\'s condition and advise on repair vs. replacement.' },
        { q: 'Should I repair or replace my water heater?', a: 'Generally, if your unit is over 10 years old and the repair costs more than 50% of a new unit, replacement is the better investment. We always provide honest advice based on your specific situation.' },
        { q: 'Do you offer water heater maintenance?', a: 'Yes. Annual flushing and inspection extends the life of your water heater by 3-5 years and improves energy efficiency. Ask about our maintenance plans.' },
      ],
      relatedServices: ['water-heater-installation', 'tankless-water-heaters', 'residential-plumbing'],
    },
    {
      id: 'water-heater-installation',
      title: 'Water Heater Installation',
      icon: 'waterHeater',
      category: 'water-heaters',
      shortDesc: 'Professional water heater installation with proper sizing, permitting, and code-compliant hookup. All brands and types available.',
      description: 'Whether you\'re replacing an old unit or installing a water heater in a new construction, PrimeFlow Plumbing handles every aspect of the installation process. We help you choose the right type and size for your household\'s hot water demands, handle all necessary permits, and ensure code-compliant installation. Our installations include proper venting, gas or electrical connections, expansion tanks, and seismic strapping where required.',
      processSteps: ['In-home assessment and sizing', 'Product selection and quote', 'Old unit removal and disposal', 'Professional installation and testing'],
      benefits: ['Free in-home consultation', 'Right-sized for your household', 'All permits handled', 'Code-compliant installation', 'Old unit removal included', 'Manufacturer warranty honored'],
      commonProblems: ['Aging water heater past 10 years', 'Not enough hot water for household', 'High energy bills from old unit', 'Frequent repairs needed', 'Upgrading to energy-efficient model', 'New construction or remodel needs'],
      faqs: [
        { q: 'What size water heater do I need?', a: 'For a family of 4, we typically recommend a 50-gallon tank or a properly sized tankless unit. We calculate based on peak demand, number of bathrooms, and usage patterns.' },
        { q: 'How long does installation take?', a: 'A standard tank water heater replacement typically takes 2-4 hours. Tankless installations or conversions from tank to tankless may take a full day.' },
        { q: 'Do you remove and dispose of the old unit?', a: 'Yes, removal and disposal of your old water heater is included in every installation.' },
      ],
      relatedServices: ['water-heater-repair', 'tankless-water-heaters', 'gas-line-services'],
    },
    {
      id: 'tankless-water-heaters',
      title: 'Tankless Water Heaters',
      icon: 'tankless',
      category: 'water-heaters',
      shortDesc: 'Endless hot water with energy-efficient tankless water heater installation, repair, and maintenance services.',
      description: 'Tankless water heaters provide unlimited hot water on demand while using significantly less energy than traditional tanks. PrimeFlow Plumbing specializes in tankless water heater installation, repair, and maintenance for leading brands like Navien, Rinnai, and Noritz. We assess your home\'s hot water needs, gas line capacity, and venting requirements to ensure optimal performance. Tankless units can save up to 34% on energy costs and last twice as long as traditional tanks.',
      processSteps: ['Home assessment for tankless suitability', 'Size calculation and product selection', 'Professional installation with proper venting', 'System setup, testing, and user training'],
      benefits: ['Unlimited hot water on demand', 'Up to 34% energy savings', '15-20 year average lifespan', 'Space-saving wall-mounted design', 'Reduced risk of water damage', 'Lower long-term operating costs'],
      commonProblems: ['Want to upgrade from tank to tankless', 'Existing tankless not heating enough', 'Error codes on tankless display', 'Mineral buildup reducing performance', 'Need tankless descaling service', 'Cold water sandwich effect'],
      faqs: [
        { q: 'Can my home support a tankless water heater?', a: 'Most homes can be fitted for tankless, but it requires adequate gas supply and proper venting. We provide a free assessment to determine if your home is a good candidate.' },
        { q: 'How much can I save with tankless?', a: 'Most homeowners save $80-$150 annually on energy costs. The savings increase with a longer ownership period since tankless units last 15-20 years versus 8-12 for tanks.' },
        { q: 'Do tankless water heaters need maintenance?', a: 'Yes, annual descaling is recommended, especially in areas with hard water. We offer maintenance plans to keep your unit running at peak efficiency.' },
      ],
      relatedServices: ['water-heater-installation', 'water-heater-repair', 'gas-line-services'],
    },
    {
      id: 'sewer-line-repair',
      title: 'Sewer Line Repair',
      icon: 'sewer',
      category: 'drains',
      shortDesc: 'Complete sewer line repair and replacement including trenchless options. We fix collapsed, cracked, and root-invaded sewer lines.',
      description: 'Sewer line problems can cause serious property damage and health hazards. PrimeFlow Plumbing provides comprehensive sewer line repair services including traditional excavation and modern trenchless methods like pipe bursting and pipe lining. We use advanced sewer camera inspection to pinpoint the exact location and nature of the problem before recommending the most cost-effective repair strategy. Our team handles everything from minor spot repairs to full sewer line replacement.',
      processSteps: ['Sewer camera inspection', 'Damage assessment and repair plan', 'Professional repair or replacement', 'Final inspection and verification'],
      benefits: ['Trenchless repair options available', 'Sewer camera inspection included', 'Minimal disruption to landscaping', 'Long-lasting repair methods', 'Full sewer line replacement available', 'All permits and inspections handled'],
      commonProblems: ['Sewage backing up into home', 'Multiple drains clogging simultaneously', 'Foul odors in yard', 'Soggy patches in lawn', 'Tree root intrusion', 'Collapsed or bellied sewer pipe', 'Old clay or cast iron pipe deterioration'],
      faqs: [
        { q: 'What is trenchless sewer repair?', a: 'Trenchless methods allow us to repair or replace your sewer line without digging up your entire yard. We access the pipe through small entry points and use pipe lining or pipe bursting techniques.' },
        { q: 'How do I know if my sewer line needs repair?', a: 'Warning signs include multiple slow drains, sewage odors, gurgling sounds, soggy spots in your yard, or sewage backup. A camera inspection can confirm the condition of your line.' },
        { q: 'How long does sewer line repair take?', a: 'Trenchless repairs can often be completed in one day. Traditional excavation repairs typically take 2-3 days depending on the extent of damage and yard conditions.' },
      ],
      relatedServices: ['drain-cleaning', 'hydro-jetting', 'pipe-repair'],
    },
    {
      id: 'leak-detection',
      title: 'Leak Detection',
      icon: 'leak',
      category: 'repair',
      shortDesc: 'Advanced electronic and thermal leak detection to find hidden leaks in walls, floors, and underground pipes without destructive investigation.',
      description: 'Hidden water leaks can cause extensive structural damage, mold growth, and skyrocketing water bills. PrimeFlow Plumbing uses advanced leak detection technology including electronic listening devices, thermal imaging, and pressure testing to pinpoint the exact location of leaks without tearing apart your walls or floors. Our non-invasive approach saves you money on unnecessary demolition and gets to the root of the problem quickly.',
      processSteps: ['Water meter analysis and pressure test', 'Electronic and thermal scanning', 'Pinpoint leak location identified', 'Targeted repair with minimal disruption'],
      benefits: ['Non-invasive detection technology', 'Pinpoint accuracy saves repair costs', 'Electronic listening devices', 'Thermal imaging available', 'Underground pipe location', 'Pressure testing included'],
      commonProblems: ['Unexplained high water bills', 'Sound of running water when nothing is on', 'Damp spots on walls or ceilings', 'Mold or mildew growth', 'Foundation cracks from water damage', 'Hot spots on floors (slab leak)', 'Low water pressure'],
      faqs: [
        { q: 'How do you find leaks without opening walls?', a: 'We use electronic listening equipment that amplifies the sound of escaping water, thermal imaging cameras that detect temperature differences, and pressure testing to isolate leak locations precisely.' },
        { q: 'How much does leak detection cost?', a: 'Leak detection is a fraction of the cost of exploratory demolition. The service typically pays for itself by allowing targeted, minimal-disruption repairs.' },
        { q: 'Can you detect slab leaks?', a: 'Yes, we specialize in slab leak detection using electronic and thermal methods. These are among the most challenging leaks to find, and our technology locates them without jackhammering your floor.' },
      ],
      relatedServices: ['pipe-repair', 'emergency-plumbing', 'whole-home-repiping'],
    },
    {
      id: 'pipe-repair',
      title: 'Pipe Repair',
      icon: 'pipe',
      category: 'repair',
      shortDesc: 'Fast, reliable pipe repair for leaks, cracks, corrosion, and burst pipes. We fix copper, PVC, PEX, galvanized, and cast iron pipes.',
      description: 'From a minor pinhole leak to a major pipe burst, PrimeFlow Plumbing provides expert pipe repair services for all pipe materials and sizes. Our licensed plumbers work with copper, PVC, CPVC, PEX, galvanized steel, and cast iron to deliver lasting repairs that meet code. We carry a wide range of fittings and materials on our trucks to handle most repairs on the first visit, minimizing disruption to your home.',
      processSteps: ['Leak location and pipe assessment', 'Repair method recommendation', 'Professional pipe repair', 'Pressure test and leak verification'],
      benefits: ['All pipe materials serviced', 'Most repairs completed same visit', 'Code-compliant workmanship', 'Lasting repairs, not patches', 'Minimal wall/floor disruption', 'Written warranty on repairs'],
      commonProblems: ['Leaking pipe joints', 'Corroded galvanized pipes', 'Frozen pipe damage', 'Pinhole leaks in copper', 'Cracked PVC pipes', 'Cast iron pipe deterioration', 'Pipe joint failure'],
      faqs: [
        { q: 'Can you repair a pipe without replacing the whole section?', a: 'In many cases, yes. We use spot repair techniques, pipe clamps, and epoxy methods when appropriate. For more extensive damage, section replacement ensures long-term reliability.' },
        { q: 'What pipe material is best for repairs?', a: 'We match the repair material to your existing system. For new installations, we often recommend PEX for its flexibility, durability, and resistance to freezing.' },
        { q: 'Do you repair pipes inside walls and ceilings?', a: 'Yes. We combine leak detection technology with targeted access to minimize the amount of drywall or flooring that needs to be opened for the repair.' },
      ],
      relatedServices: ['leak-detection', 'whole-home-repiping', 'frozen-pipe-repair', 'emergency-plumbing'],
    },
    {
      id: 'whole-home-repiping',
      title: 'Whole Home Repiping',
      icon: 'repiping',
      category: 'repair',
      shortDesc: 'Complete whole-home repiping to replace old, corroded, or failing plumbing with modern, durable pipe systems.',
      description: 'If your home has galvanized steel, polybutylene, or aging copper pipes that are failing throughout the house, whole-home repiping is the permanent solution. PrimeFlow Plumbing replaces your entire water supply system with modern PEX or copper piping, eliminating recurring leaks, improving water pressure, and protecting your home from future failures. We work efficiently to minimize disruption, typically completing a full repipe in 2-3 days.',
      processSteps: ['Comprehensive plumbing assessment', 'Custom repiping plan and quote', 'Systematic pipe replacement', 'Inspection, testing, and wall patching'],
      benefits: ['Eliminates recurring pipe failures', 'Dramatically improved water pressure', 'Modern materials with 50+ year life', 'Increases home value', 'Removes lead and corrosion risks', 'Typically completed in 2-3 days'],
      commonProblems: ['Frequent pipe leaks throughout home', 'Galvanized pipe corrosion', 'Polybutylene pipe failure risk', 'Low water pressure from buildup', 'Rusty or discolored water', 'Lead pipe concerns', 'Home remodel requiring updated plumbing'],
      faqs: [
        { q: 'How long does a whole home repipe take?', a: 'Most homes can be fully repiped in 2-3 days. Larger homes or complex layouts may take up to 5 days. We work room by room to maintain water access during the project.' },
        { q: 'Do you patch the walls after repiping?', a: 'We include basic drywall patching as part of our repipe service. For complete wall finishing and painting, we can recommend trusted contractors.' },
        { q: 'Is PEX better than copper for repiping?', a: 'PEX is generally our recommendation for repipes due to its flexibility, freeze resistance, lower cost, and 50+ year lifespan. Copper remains an excellent choice and we install both.' },
      ],
      relatedServices: ['pipe-repair', 'leak-detection', 'residential-plumbing'],
    },
    {
      id: 'toilet-repair',
      title: 'Toilet Repair',
      icon: 'toilet',
      category: 'fixtures',
      shortDesc: 'Expert toilet repair and replacement for running toilets, clogs, leaks, and upgrades to water-efficient models.',
      description: 'A running, leaking, or constantly clogging toilet wastes water and causes frustration. PrimeFlow Plumbing handles all toilet repairs including flapper replacement, fill valve repair, wax ring replacement, handle mechanisms, and more. We also install new toilets when repair isn\'t the best option, including water-efficient models that can save hundreds of gallons per year. Our technicians arrive with the parts and tools to resolve most toilet issues in a single visit.',
      processSteps: ['Diagnosis of toilet issue', 'Repair recommendation and quote', 'Professional repair or replacement', 'Flush test and leak check'],
      benefits: ['Most repairs done in one visit', 'All toilet brands serviced', 'Water-efficient upgrades available', 'Wax ring and flange repairs', 'New toilet installation', 'Clean and respectful service'],
      commonProblems: ['Toilet running continuously', 'Weak or incomplete flush', 'Toilet leaking at base', 'Constant clogging', 'Loose or wobbly toilet', 'Ghost flushing', 'Cracked tank or bowl'],
      faqs: [
        { q: 'Why does my toilet keep running?', a: 'The most common causes are a worn flapper, faulty fill valve, or incorrect float adjustment. These are typically quick, affordable repairs that save significant water.' },
        { q: 'Should I repair or replace my toilet?', a: 'If your toilet is over 15 years old, requires frequent repairs, or uses more than 1.6 gallons per flush, upgrading to a new WaterSense toilet is usually the better investment.' },
        { q: 'Can you install a bidet seat?', a: 'Yes, we install bidet seats and bidet attachments on most standard toilets. This includes the necessary water supply connection.' },
      ],
      relatedServices: ['bathroom-plumbing', 'residential-plumbing', 'faucet-repair'],
    },
    {
      id: 'faucet-repair',
      title: 'Faucet Repair',
      icon: 'faucet',
      category: 'fixtures',
      shortDesc: 'Professional faucet repair and installation for kitchens, bathrooms, and utility sinks. We fix drips, leaks, and low pressure.',
      description: 'A dripping faucet can waste over 3,000 gallons of water per year and drive up your utility bills. PrimeFlow Plumbing provides expert faucet repair for all types and brands, including single-handle, double-handle, pull-down, touchless, and commercial faucets. We also install new faucets with precision, ensuring proper connections and leak-free operation. Whether it\'s a simple cartridge replacement or a complete faucet upgrade, we handle it all.',
      processSteps: ['Assess faucet condition and type', 'Diagnose specific issue', 'Repair or replace components', 'Test operation and check for leaks'],
      benefits: ['All faucet types and brands', 'Stop water waste from drips', 'New faucet installation available', 'Cartridge and valve replacement', 'Improved water pressure', 'Clean, professional installation'],
      commonProblems: ['Dripping faucet', 'Low water pressure', 'Faucet handle difficult to turn', 'Leaking under sink', 'Sprayer not working', 'Hot/cold reversed', 'Corroded or outdated faucet'],
      faqs: [
        { q: 'Can you repair any faucet brand?', a: 'Yes, we service all major brands including Moen, Delta, Kohler, Pfister, American Standard, and more. We carry common replacement parts for popular models.' },
        { q: 'How much water does a dripping faucet waste?', a: 'A faucet dripping once per second wastes over 3,000 gallons per year. That\'s enough to take over 180 showers. Fixing a drip is always worth it.' },
        { q: 'Can I just replace the faucet cartridge?', a: 'Often, yes. Cartridge replacement is the most common faucet repair and costs a fraction of a new faucet. We\'ll diagnose whether repair or replacement is the better option.' },
      ],
      relatedServices: ['sink-installation', 'kitchen-plumbing', 'bathroom-plumbing'],
    },
    {
      id: 'sink-installation',
      title: 'Sink Installation',
      icon: 'sink',
      category: 'fixtures',
      shortDesc: 'Professional sink installation for kitchens, bathrooms, laundry rooms, and utility areas. Drop-in, undermount, farmhouse, and vessel sinks.',
      description: 'Whether you\'re upgrading your kitchen with a farmhouse sink, adding a vessel sink to a bathroom remodel, or installing a utility sink in your laundry room, PrimeFlow Plumbing handles every aspect of sink installation. We ensure proper drainage connections, water supply hookups, and seamless integration with your countertop and cabinetry. We also handle garbage disposal connections, soap dispensers, and filtration system hookups.',
      processSteps: ['Review sink type and installation requirements', 'Prepare plumbing connections', 'Install sink with proper sealing', 'Connect supply lines and test drainage'],
      benefits: ['All sink types installed', 'Kitchen, bath, and utility sinks', 'Proper drainage slope ensured', 'Supply line upgrades included', 'Garbage disposal hookup available', 'Clean, leak-free installation'],
      commonProblems: ['Upgrading sink during remodel', 'Replacing damaged or stained sink', 'Adding new sink to space', 'Converting from drop-in to undermount', 'Utility sink installation', 'Sink drain leaking'],
      faqs: [
        { q: 'Can you install an undermount sink?', a: 'Yes, we install all sink types including undermount, drop-in, farmhouse/apron, vessel, and wall-mount sinks. We ensure proper support and sealing for each type.' },
        { q: 'Do I need to buy the sink myself?', a: 'You\'re welcome to purchase your own sink or we can help you select the right one for your needs. We work with all major brands and can source quality sinks at competitive prices.' },
        { q: 'Do you handle the countertop cut for a new sink?', a: 'For plumbing modifications, yes. For stone countertop cuts, we coordinate with countertop specialists to ensure a perfect fit.' },
      ],
      relatedServices: ['faucet-repair', 'garbage-disposal', 'kitchen-plumbing'],
    },
    {
      id: 'garbage-disposal',
      title: 'Garbage Disposal',
      icon: 'disposal',
      category: 'fixtures',
      shortDesc: 'Garbage disposal installation, repair, and replacement. We service InSinkErator, Waste King, Moen, and all major brands.',
      description: 'A properly functioning garbage disposal is essential for a modern kitchen. PrimeFlow Plumbing provides expert installation, repair, and replacement of garbage disposals from all major brands. Whether your disposal is jammed, leaking, making unusual noises, or simply needs upgrading to a more powerful model, our technicians handle it quickly and cleanly. We ensure proper electrical connections, mounting, and drain hookups for reliable, long-lasting performance.',
      processSteps: ['Assess current disposal or needs', 'Recommend repair or replacement', 'Professional installation or repair', 'Test operation and drainage'],
      benefits: ['All brands serviced and installed', 'Same-day service available', 'Proper electrical connections', 'Dishwasher drain hookup included', 'Quiet operation models available', 'Clean removal of old unit'],
      commonProblems: ['Disposal not turning on', 'Jammed disposal', 'Leaking from bottom', 'Unusual grinding noises', 'Slow drainage from disposal', 'Old disposal needs upgrading', 'New installation needed'],
      faqs: [
        { q: 'What size garbage disposal do I need?', a: 'For most households, a 1/2 HP unit is sufficient. Larger families or those who cook frequently should consider 3/4 HP or 1 HP models for better performance.' },
        { q: 'Can you install a disposal if I don\'t have one?', a: 'Yes, we can add a garbage disposal to most kitchen sinks. This includes the necessary electrical and plumbing connections.' },
        { q: 'My disposal is humming but not spinning. Can it be fixed?', a: 'Usually, yes. A humming disposal typically indicates a jam. We can often clear the obstruction and restore function without replacement.' },
      ],
      relatedServices: ['sink-installation', 'kitchen-plumbing', 'drain-cleaning'],
    },
    {
      id: 'sump-pump-repair',
      title: 'Sump Pump Repair',
      icon: 'sumpPump',
      category: 'specialty',
      shortDesc: 'Sump pump repair, replacement, and installation to protect your basement from flooding. Battery backup systems available.',
      description: 'In Northeastern Pennsylvania, a reliable sump pump is your first defense against basement flooding. PrimeFlow Plumbing provides comprehensive sump pump services including repair, replacement, and new installation. We service all types of sump pumps — submersible, pedestal, and combination units with battery backup. Living in NEPA means dealing with heavy rain, spring snowmelt, and high water tables, making a properly functioning sump pump essential for protecting your home.',
      processSteps: ['Inspect sump pit and pump system', 'Diagnose issue or assess needs', 'Repair or replace pump', 'Test operation and backup systems'],
      benefits: ['All sump pump types serviced', 'Battery backup systems available', 'Check valve installation', 'Sump pit cleaning included', 'Emergency replacement available', 'Preventive maintenance plans'],
      commonProblems: ['Pump not turning on', 'Pump running but not removing water', 'Unusual noises from pump', 'Pump cycling on and off rapidly', 'No battery backup during power outages', 'Old pump past its lifespan', 'Basement flooding during storms'],
      faqs: [
        { q: 'How often should I replace my sump pump?', a: 'Sump pumps typically last 7-10 years. We recommend replacement before failure to prevent flooding, especially before spring thaw season in NEPA.' },
        { q: 'Do I need a battery backup sump pump?', a: 'We strongly recommend battery backup for all homes with sump pumps. Power outages often coincide with severe storms — exactly when you need your pump most.' },
        { q: 'How do I maintain my sump pump?', a: 'Test your pump quarterly by pouring water into the pit. Check the discharge line for obstructions and ensure the float switch moves freely. We offer annual maintenance service as well.' },
      ],
      relatedServices: ['emergency-plumbing', 'residential-plumbing', 'water-filtration'],
    },
    {
      id: 'water-filtration',
      title: 'Water Filtration',
      icon: 'filter',
      category: 'specialty',
      shortDesc: 'Whole-home and point-of-use water filtration systems to improve water quality, taste, and safety for your family.',
      description: 'Clean, safe water is essential for your family\'s health. PrimeFlow Plumbing installs and services whole-home water filtration systems, under-sink filters, reverse osmosis systems, and water softeners. We test your water to identify specific contaminants and recommend the right filtration solution for your needs. Whether you\'re dealing with hard water, chlorine taste, sediment, iron, or other water quality concerns, we have the solution.',
      processSteps: ['Water quality testing and analysis', 'Custom filtration recommendation', 'Professional system installation', 'Water quality verification and maintenance plan'],
      benefits: ['Free water quality testing', 'Whole-home and point-of-use options', 'Water softener installation', 'Reverse osmosis systems', 'Filter replacement service', 'Improved taste and safety'],
      commonProblems: ['Hard water causing scale buildup', 'Chlorine taste or smell', 'Sediment in water', 'Iron staining on fixtures', 'Concern about water contaminants', 'Well water treatment needs', 'Bottled water alternative desired'],
      faqs: [
        { q: 'Do I need a whole-home system or just an under-sink filter?', a: 'It depends on your water quality concerns. If you have hard water or widespread quality issues, whole-home is best. For drinking water taste improvement, an under-sink RO system may be sufficient.' },
        { q: 'How often do filters need replacing?', a: 'It varies by system type. Sediment pre-filters every 3-6 months, carbon filters every 6-12 months, and RO membranes every 2-3 years. We offer maintenance plans for hassle-free filter changes.' },
        { q: 'Can you treat well water?', a: 'Absolutely. We specialize in well water treatment including UV disinfection, iron removal, pH correction, and comprehensive filtration systems tailored to your well water test results.' },
      ],
      relatedServices: ['residential-plumbing', 'sink-installation', 'whole-home-repiping'],
    },
    {
      id: 'bathroom-plumbing',
      title: 'Bathroom Plumbing',
      icon: 'bathroom',
      category: 'rooms',
      shortDesc: 'Complete bathroom plumbing services from fixture installation to full bathroom remodels. Showers, tubs, toilets, sinks, and more.',
      description: 'From a simple faucet swap to a complete bathroom renovation, PrimeFlow Plumbing handles all aspects of bathroom plumbing. We install and repair toilets, sinks, faucets, showers, bathtubs, and all associated plumbing. Our team works with homeowners and contractors on bathroom remodels, ensuring proper rough-in, fixture placement, and code-compliant connections. We also address common bathroom plumbing issues like low water pressure, drain problems, and leaking fixtures.',
      processSteps: ['Bathroom plumbing assessment', 'Scope of work and detailed quote', 'Professional installation or repair', 'Final inspection and walkthrough'],
      benefits: ['Full bathroom remodel plumbing', 'All fixture types installed', 'Shower and tub installation', 'ADA-compliant modifications', 'Proper venting ensured', 'Coordination with contractors'],
      commonProblems: ['Bathroom remodel plumbing needs', 'Shower or tub leaking', 'Low water pressure in bathroom', 'Slow bathroom drains', 'Toilet replacement or upgrade', 'Adding a bathroom to home', 'Converting tub to walk-in shower'],
      faqs: [
        { q: 'Can you handle the plumbing for a full bathroom remodel?', a: 'Absolutely. We handle all plumbing aspects including rough-in, fixture installation, drain connections, and water supply modifications. We coordinate with your general contractor for seamless integration.' },
        { q: 'Can you add a bathroom where there isn\'t one?', a: 'Yes, we can rough in plumbing for new bathrooms in basements, additions, or converted spaces. This includes extending supply lines, adding drain connections, and ensuring proper venting.' },
        { q: 'Do you install walk-in showers and tubs?', a: 'Yes, we install all types of showers and tubs including walk-in showers, freestanding tubs, jetted tubs, and ADA-accessible units with grab bars and bench seating.' },
      ],
      relatedServices: ['toilet-repair', 'faucet-repair', 'drain-cleaning'],
    },
    {
      id: 'kitchen-plumbing',
      title: 'Kitchen Plumbing',
      icon: 'kitchen',
      category: 'rooms',
      shortDesc: 'Complete kitchen plumbing from sink and faucet installation to dishwasher hookups, garbage disposals, and kitchen remodel plumbing.',
      description: 'The kitchen is the heart of your home, and its plumbing needs to work flawlessly. PrimeFlow Plumbing provides complete kitchen plumbing services including sink and faucet installation, garbage disposal service, dishwasher hookups, ice maker lines, pot filler installation, and kitchen remodel plumbing. We also address common kitchen plumbing issues like clogged drains, leaking pipes under the sink, and low water pressure.',
      processSteps: ['Kitchen plumbing needs assessment', 'Detailed scope and pricing', 'Professional installation or repair', 'Testing and clean workspace'],
      benefits: ['Complete kitchen remodel plumbing', 'Sink and faucet expertise', 'Dishwasher hookup and repair', 'Ice maker and water line installation', 'Gas line for stove connections', 'Garbage disposal service'],
      commonProblems: ['Kitchen remodel plumbing needs', 'Clogged kitchen drain', 'Leaking under kitchen sink', 'Dishwasher not draining', 'Need ice maker water line', 'Want to add pot filler', 'Moving sink location in remodel'],
      faqs: [
        { q: 'Can you move my kitchen sink to a different location?', a: 'Yes, we can relocate kitchen sinks as part of a remodel. This involves extending water supply lines and drain connections to the new location.' },
        { q: 'Do you connect dishwashers?', a: 'Yes, we install and connect dishwashers including water supply, drain line, and ensuring proper air gap or high-loop drain to prevent backflow.' },
        { q: 'Can you install a gas line for my stove?', a: 'Yes, we provide gas line installation and connection for stoves, ranges, and other gas appliances. All gas work is performed by licensed technicians and includes leak testing.' },
      ],
      relatedServices: ['sink-installation', 'garbage-disposal', 'faucet-repair', 'drain-cleaning'],
    },
    {
      id: 'commercial-plumbing',
      title: 'Commercial Plumbing',
      icon: 'commercial',
      category: 'type',
      shortDesc: 'Professional commercial plumbing for restaurants, offices, retail, and industrial facilities throughout NEPA.',
      description: 'PrimeFlow Plumbing provides reliable commercial plumbing services for businesses of all sizes throughout Northeastern Pennsylvania. From restaurants and retail stores to office buildings and industrial facilities, we understand that plumbing problems mean lost revenue. That\'s why we offer priority commercial service, preventive maintenance contracts, and after-hours repairs to minimize downtime. Our commercial team handles everything from routine maintenance to complex new construction plumbing.',
      processSteps: ['Commercial needs assessment', 'Customized service plan', 'Professional service with minimal disruption', 'Ongoing maintenance and support'],
      benefits: ['Priority commercial scheduling', 'After-hours service available', 'Preventive maintenance contracts', 'Code compliance expertise', 'Minimal business disruption', 'Multi-location service available'],
      commonProblems: ['Restaurant grease trap issues', 'Commercial water heater failure', 'Restroom plumbing problems', 'Backflow preventer testing needed', 'New construction plumbing', 'Tenant improvement plumbing', 'Code violation remediation'],
      faqs: [
        { q: 'Do you offer commercial maintenance contracts?', a: 'Yes, we offer customizable maintenance contracts that include regular inspections, preventive maintenance, priority scheduling, and discounted repair rates.' },
        { q: 'Can you work outside business hours?', a: 'Absolutely. We schedule commercial work during off-hours, evenings, and weekends to minimize disruption to your business operations.' },
        { q: 'Do you handle commercial new construction?', a: 'Yes, our commercial team provides full plumbing services for new construction including design consultation, rough-in, fixture installation, and final inspection coordination.' },
      ],
      relatedServices: ['drain-cleaning', 'water-heater-installation', 'hydro-jetting'],
    },
    {
      id: 'residential-plumbing',
      title: 'Residential Plumbing',
      icon: 'home',
      category: 'type',
      shortDesc: 'Complete residential plumbing services for homeowners — repairs, installations, remodels, and maintenance for your entire home.',
      description: 'PrimeFlow Plumbing is your trusted partner for all home plumbing needs. From minor repairs like a dripping faucet to major projects like whole-home repiping or bathroom remodels, our licensed plumbers deliver quality workmanship backed by our satisfaction guarantee. We treat your home with respect, arriving on time, wearing shoe covers, and cleaning up completely after every job. NEPA homeowners trust PrimeFlow for reliable, fairly-priced residential plumbing.',
      processSteps: ['Schedule your appointment', 'In-home assessment and quote', 'Professional plumbing service', 'Walkthrough and satisfaction check'],
      benefits: ['Full-service residential plumbing', 'On-time guaranteed appointments', 'Shoe covers and drop cloths used', 'Upfront flat-rate pricing', 'Satisfaction guarantee on all work', 'Financing options available'],
      commonProblems: ['Annual plumbing maintenance needed', 'Multiple plumbing repairs needed', 'Home purchase plumbing inspection', 'New home plumbing installation', 'Remodel plumbing coordination', 'Plumbing upgrades for home value', 'Winterization of plumbing system'],
      faqs: [
        { q: 'Do you offer flat-rate pricing?', a: 'Yes, we provide upfront flat-rate pricing so you know the cost before we begin. No hourly surprises — the price we quote is the price you pay.' },
        { q: 'Do you offer any warranties?', a: 'All our work comes with a satisfaction guarantee and workmanship warranty. Specific warranty terms vary by service and are provided in writing with your quote.' },
        { q: 'Can I get a plumbing inspection before buying a home?', a: 'Yes, we offer pre-purchase plumbing inspections that check water heaters, supply lines, drain systems, fixtures, and sewer lines to give you a clear picture of the home\'s plumbing condition.' },
      ],
      relatedServices: ['bathroom-plumbing', 'kitchen-plumbing', 'water-heater-repair', 'drain-cleaning'],
    },
    {
      id: 'gas-line-services',
      title: 'Gas Line Services',
      icon: 'gas',
      category: 'specialty',
      shortDesc: 'Licensed gas line installation, repair, and leak detection for stoves, dryers, water heaters, fireplaces, and outdoor grills.',
      description: 'Gas line work requires licensed professionals — it\'s not a DIY project. PrimeFlow Plumbing provides expert gas line services including new line installation, leak detection and repair, appliance hookups, and gas line extensions. We install gas lines for stoves, dryers, water heaters, fireplaces, fire pits, outdoor grills, and generators. All our gas work is performed by licensed technicians and includes mandatory pressure testing and leak verification for your safety.',
      processSteps: ['Gas line assessment and planning', 'Permit acquisition', 'Professional installation or repair', 'Pressure testing and leak verification'],
      benefits: ['Licensed gas line technicians', 'All appliance types connected', 'New line installation', 'Leak detection and repair', 'Pressure testing included', 'All permits handled'],
      commonProblems: ['Gas smell detected in home', 'New gas appliance needs hookup', 'Extending gas line to new location', 'Converting electric to gas appliance', 'Outdoor grill gas line needed', 'Gas fireplace installation', 'Generator gas line connection'],
      faqs: [
        { q: 'I smell gas — what should I do?', a: 'Leave your home immediately, don\'t use any electrical switches, and call your gas company and 911 from outside. Once the area is safe, call us for leak repair.' },
        { q: 'Can you convert my electric stove to gas?', a: 'Yes, we can run a new gas line to your kitchen for a gas stove conversion. This includes the gas line, shutoff valve, and appliance connection with full pressure testing.' },
        { q: 'Do you install gas lines for outdoor kitchens?', a: 'Yes, we install gas lines for outdoor grills, fire pits, patio heaters, and full outdoor kitchen setups with proper underground or exterior routing.' },
      ],
      relatedServices: ['water-heater-installation', 'residential-plumbing', 'commercial-plumbing'],
    },
    {
      id: 'frozen-pipe-repair',
      title: 'Frozen Pipe Repair',
      icon: 'frozen',
      category: 'emergency',
      shortDesc: 'Emergency frozen pipe thawing and burst pipe repair. Protect your NEPA home during harsh Pennsylvania winters.',
      description: 'Northeastern Pennsylvania winters bring freezing temperatures that can cause pipes to freeze and burst, leading to serious water damage. PrimeFlow Plumbing provides emergency frozen pipe services including safe thawing, burst pipe repair, and preventive insulation to protect your plumbing from future freezes. Our technicians respond quickly because frozen pipes can burst at any moment, potentially causing thousands of dollars in water damage.',
      processSteps: ['Emergency response and assessment', 'Safe pipe thawing techniques', 'Burst pipe repair if needed', 'Insulation and prevention measures'],
      benefits: ['Emergency response available', 'Safe thawing methods used', 'Burst pipe repair included', 'Pipe insulation service', 'Heat tape installation', 'Winterization services available'],
      commonProblems: ['No water from specific faucet in winter', 'Visible frost on exposed pipes', 'Bulging or cracked pipe', 'Water damage from burst pipe', 'Crawl space pipes freezing', 'Exterior hose bib frozen', 'Pipes in unheated areas at risk'],
      faqs: [
        { q: 'How do I know if my pipes are frozen?', a: 'Signs include no water flow from a faucet, unusual sounds when turning on water, visible frost on exposed pipes, or a foul smell from the drain (indicating a sewer pipe may be frozen).' },
        { q: 'Should I try to thaw frozen pipes myself?', a: 'You can safely apply gentle heat (hair dryer, heat lamp) to accessible frozen pipes. Never use open flames. If you can\'t find or access the frozen section, call us immediately.' },
        { q: 'How can I prevent pipes from freezing?', a: 'Keep cabinet doors open during cold snaps, let faucets drip, maintain heat at 55°F+ even when away, and insulate pipes in crawl spaces and exterior walls. We offer professional pipe insulation and heat tape installation.' },
      ],
      relatedServices: ['emergency-plumbing', 'pipe-repair', 'residential-plumbing'],
    },
    {
      id: 'hydro-jetting',
      title: 'Hydro Jetting',
      icon: 'hydroJet',
      category: 'drains',
      shortDesc: 'High-pressure hydro jetting service to blast away grease, roots, scale, and stubborn blockages from drain and sewer lines.',
      description: 'Hydro jetting is the most effective method for cleaning drain and sewer lines. PrimeFlow Plumbing uses high-pressure water jetting at up to 4,000 PSI to blast away grease, tree roots, mineral scale, and stubborn blockages that traditional snaking can\'t fully clear. This method thoroughly cleans the interior walls of your pipes, restoring them to near-original diameter and preventing future clogs. Hydro jetting is safe for most pipe materials and is the preferred method for commercial and residential sewer maintenance.',
      processSteps: ['Camera inspection to assess pipe condition', 'Select appropriate jetting pressure', 'Systematic hydro jetting of lines', 'Post-cleaning camera verification'],
      benefits: ['Clears the toughest blockages', 'Removes tree roots effectively', 'Cleans entire pipe interior', 'Prevents future clogs', 'Safe for most pipe materials', 'Camera inspection included'],
      commonProblems: ['Recurring drain clogs', 'Tree root intrusion', 'Grease buildup in restaurant lines', 'Scale buildup in pipes', 'Slow main sewer line', 'Preparing for pipe lining', 'Commercial kitchen drain maintenance'],
      faqs: [
        { q: 'Is hydro jetting safe for old pipes?', a: 'We always camera-inspect pipes before jetting to assess their condition. While hydro jetting is safe for most pipe materials, we adjust pressure or recommend alternatives for fragile or damaged pipes.' },
        { q: 'How is hydro jetting different from snaking?', a: 'Snaking punches through blockages but leaves residue on pipe walls. Hydro jetting uses high-pressure water to scour the entire interior of the pipe, providing a much more thorough cleaning.' },
        { q: 'How often should sewer lines be hydro jetted?', a: 'For residential, every 1-2 years if you have recurring issues or trees near your sewer line. Commercial kitchens and restaurants should consider quarterly or semi-annual jetting.' },
      ],
      relatedServices: ['drain-cleaning', 'sewer-line-repair', 'commercial-plumbing'],
    },
    {
      id: 'boiler-plumbing-services',
      title: 'Boiler Plumbing Services',
      icon: 'boiler',
      category: 'specialty',
      shortDesc: 'Boiler plumbing repair, maintenance, and installation. We service hydronic heating systems, expansion tanks, circulators, and boiler piping.',
      description: 'Many NEPA homes rely on boiler systems for heat, and the plumbing components of these systems require specialized expertise. PrimeFlow Plumbing services the plumbing side of boiler systems including circulation pumps, expansion tanks, zone valves, pressure relief valves, boiler piping, and radiator connections. We also provide boiler winterization, seasonal startup, and preventive maintenance to keep your heating system running efficiently through harsh Pennsylvania winters.',
      processSteps: ['Boiler system plumbing inspection', 'Diagnose component issues', 'Professional repair or replacement', 'System pressure test and verification'],
      benefits: ['Hydronic system expertise', 'Circulator pump repair', 'Expansion tank replacement', 'Zone valve service', 'Radiator and baseboard connections', 'Seasonal maintenance available'],
      commonProblems: ['No heat from boiler system', 'Boiler losing pressure', 'Radiators not heating evenly', 'Circulator pump failure', 'Expansion tank waterlogged', 'Zone valve not opening/closing', 'Boiler piping leaks'],
      faqs: [
        { q: 'Do you work on the boiler itself or just the plumbing?', a: 'We handle the plumbing components of boiler systems — piping, circulators, expansion tanks, zone valves, and radiator connections. For burner or combustion issues, we coordinate with HVAC specialists.' },
        { q: 'How often should boiler plumbing be serviced?', a: 'We recommend annual boiler plumbing maintenance before heating season. This includes checking pressure, inspecting for leaks, testing relief valves, and bleeding radiators.' },
        { q: 'Can you add zones to my boiler heating system?', a: 'Yes, we can add heating zones for better comfort control. This involves installing zone valves, circulators, and thermostats to allow independent temperature control in different areas of your home.' },
      ],
      relatedServices: ['residential-plumbing', 'pipe-repair', 'water-heater-repair'],
    },
  ],

  serviceCategories: [
    { id: 'emergency', label: 'Emergency Services', icon: 'emergency' },
    { id: 'drains', label: 'Drain & Sewer', icon: 'drain' },
    { id: 'water-heaters', label: 'Water Heaters', icon: 'waterHeater' },
    { id: 'repair', label: 'Pipe & Leak Repair', icon: 'pipe' },
    { id: 'fixtures', label: 'Fixtures & Installation', icon: 'faucet' },
    { id: 'rooms', label: 'Room Plumbing', icon: 'home' },
    { id: 'specialty', label: 'Specialty Services', icon: 'filter' },
    { id: 'type', label: 'Service Types', icon: 'commercial' },
  ],

  locations: [
    {
      id: 'scranton',
      name: 'Scranton',
      slug: 'scranton',
      state: 'PA',
      heroTitle: 'Trusted Plumbing Services in Scranton, PA',
      description: 'PrimeFlow Plumbing proudly serves Scranton and surrounding communities with premium residential and commercial plumbing services. As the largest city in Northeastern Pennsylvania, Scranton homeowners and businesses rely on us for everything from emergency plumbing and drain cleaning to water heater installation and sewer line repair. With aging infrastructure in many Scranton neighborhoods, our repiping and pipe repair expertise is especially valued by local homeowners.',
      highlights: ['Serving all Scranton neighborhoods', 'Familiar with local building codes', 'Quick response times in the city', 'Experienced with older Scranton homes'],
      nearbyAreas: ['Dunmore', 'Clarks Summit', 'Old Forge', 'Moosic', 'Taylor', 'Dickson City'],
      faqs: [
        { q: 'How quickly can you reach Scranton for an emergency?', a: 'We typically arrive within 30-60 minutes for emergency calls in the Scranton area. Our service vehicles are strategically located for fast NEPA response.' },
        { q: 'Do you work with Scranton building codes?', a: 'Absolutely. We\'re fully familiar with Scranton and Lackawanna County building codes and handle all necessary permits for your plumbing project.' },
      ],
    },
    {
      id: 'wilkes-barre',
      name: 'Wilkes-Barre',
      slug: 'wilkes-barre',
      state: 'PA',
      heroTitle: 'Professional Plumbing in Wilkes-Barre, PA',
      description: 'PrimeFlow Plumbing provides reliable, professional plumbing services to Wilkes-Barre and the Wyoming Valley. From the historic downtown to surrounding residential areas, we handle all plumbing needs for homes and businesses. Wilkes-Barre\'s mix of historic and modern properties requires plumbers who understand both older plumbing systems and contemporary installations — that\'s exactly what our experienced team delivers.',
      highlights: ['Wyoming Valley service coverage', 'Historic home plumbing specialists', 'Commercial district service', 'Flood-prone area sump pump experts'],
      nearbyAreas: ['Kingston', 'Forty Fort', 'Edwardsville', 'Plains', 'Nanticoke', 'Hanover Township'],
      faqs: [
        { q: 'Do you service the entire Wyoming Valley?', a: 'Yes, we serve all communities in the Wyoming Valley including Kingston, Forty Fort, Edwardsville, Plains, Nanticoke, and surrounding areas.' },
        { q: 'Can you help with flood prevention plumbing?', a: 'Absolutely. Given the Wyoming Valley\'s flood history, we specialize in sump pump installation, backup sump systems, and flood prevention plumbing solutions.' },
      ],
    },
    {
      id: 'pittston',
      name: 'Pittston',
      slug: 'pittston',
      state: 'PA',
      heroTitle: 'Quality Plumbing Services in Pittston, PA',
      description: 'PrimeFlow Plumbing is the trusted plumber for Pittston and surrounding communities including West Pittston, Dupont, and Hughestown. Whether you need routine plumbing maintenance, emergency repairs, or a complete bathroom remodel, our licensed plumbers deliver quality work at fair prices. We understand the plumbing challenges common to Pittston homes, from aging pipes to seasonal freeze concerns.',
      highlights: ['Local Pittston area service', 'Quick response from nearby base', 'Familiar with Pittston home styles', 'Community-focused service'],
      nearbyAreas: ['West Pittston', 'Dupont', 'Hughestown', 'Yatesville', 'Avoca', 'Duryea'],
      faqs: [
        { q: 'Are you local to the Pittston area?', a: 'Yes, we\'re based in NEPA and Pittston is within our core service area. We provide fast response times and personalized service to the Pittston community.' },
        { q: 'Do you handle plumbing for older Pittston homes?', a: 'Absolutely. Many Pittston homes have older plumbing systems that we specialize in servicing, repairing, and upgrading while respecting the character of your home.' },
      ],
    },
    {
      id: 'hazleton',
      name: 'Hazleton',
      slug: 'hazleton',
      state: 'PA',
      heroTitle: 'Expert Plumbing Services in Hazleton, PA',
      description: 'PrimeFlow Plumbing serves the greater Hazleton area with full-service residential and commercial plumbing. Located in Luzerne County, Hazleton\'s growing community needs reliable plumbers who can handle everything from basic repairs to complex installations. Our team provides prompt, professional service to Hazleton homes and businesses, including emergency response when plumbing problems can\'t wait.',
      highlights: ['Serving greater Hazleton area', 'Residential and commercial service', 'Emergency response available', 'Growing community partner'],
      nearbyAreas: ['West Hazleton', 'Drums', 'Sugarloaf', 'Conyngham', 'Freeland', 'McAdoo'],
      faqs: [
        { q: 'Do you service the Hazleton Heights area?', a: 'Yes, we service all of Hazleton including Hazleton Heights, West Hazleton, and surrounding communities in the greater Hazleton area.' },
        { q: 'What are your Hazleton service hours?', a: 'We provide regular service Monday through Saturday, with 24/7 emergency plumbing available for urgent issues in the Hazleton area.' },
      ],
    },
    {
      id: 'allentown',
      name: 'Allentown',
      slug: 'allentown',
      state: 'PA',
      heroTitle: 'Premium Plumbing Services in Allentown, PA',
      description: 'PrimeFlow Plumbing extends our premium service to the Allentown and Lehigh Valley area. As one of Pennsylvania\'s fastest-growing regions, Allentown homeowners and businesses need plumbers who deliver quality, reliability, and professionalism. From new construction plumbing to emergency repairs, our licensed team provides the full range of plumbing services to keep Allentown homes and businesses flowing smoothly.',
      highlights: ['Lehigh Valley service area', 'New construction expertise', 'Commercial and residential', 'Fast-growing area specialists'],
      nearbyAreas: ['Bethlehem', 'Easton', 'Whitehall', 'Emmaus', 'Macungie', 'Catasauqua'],
      faqs: [
        { q: 'Do you cover the entire Lehigh Valley?', a: 'We serve Allentown and key surrounding areas. For specific location availability, please call us and we\'ll confirm coverage for your address.' },
        { q: 'Can you handle new construction plumbing?', a: 'Yes, we provide complete new construction plumbing services including design consultation, rough-in, fixture installation, and final inspection coordination.' },
      ],
    },
    {
      id: 'east-stroudsburg',
      name: 'East Stroudsburg',
      slug: 'east-stroudsburg',
      state: 'PA',
      heroTitle: 'Reliable Plumbing in East Stroudsburg, PA',
      description: 'PrimeFlow Plumbing serves East Stroudsburg and the Pocono region with dependable residential and commercial plumbing services. The Poconos present unique plumbing challenges including vacation homes that need winterization, well water systems, and properties affected by seasonal temperature extremes. Our team has the local expertise to handle these challenges while delivering the premium service PrimeFlow is known for.',
      highlights: ['Pocono region specialists', 'Vacation home winterization', 'Well water system expertise', 'Seasonal property management'],
      nearbyAreas: ['Stroudsburg', 'Marshalls Creek', 'Bushkill', 'Delaware Water Gap', 'Mount Pocono', 'Tannersville'],
      faqs: [
        { q: 'Do you winterize vacation homes?', a: 'Yes, we provide complete winterization services for seasonal and vacation properties in the Poconos, including draining pipes, setting antifreeze, and shutting down water heaters.' },
        { q: 'Can you service well water systems?', a: 'Absolutely. Many Pocono properties use well water. We service well pumps, pressure tanks, filtration systems, and all associated plumbing.' },
      ],
    },
    {
      id: 'nearby-nepa-towns',
      name: 'NEPA Communities',
      slug: 'nearby-nepa-towns',
      state: 'PA',
      heroTitle: 'Plumbing Services Across Northeastern PA',
      description: 'PrimeFlow Plumbing proudly serves communities throughout all of Northeastern Pennsylvania. From the Wyoming Valley to the Pocono Mountains, from Carbondale to Nanticoke, our service area covers dozens of towns and townships across Lackawanna, Luzerne, Monroe, Wayne, and Pike counties. If you\'re in NEPA, we\'re your local plumbing experts.',
      highlights: ['Multi-county coverage', 'Rural and suburban service', 'Local community knowledge', 'Reliable NEPA-wide response'],
      nearbyAreas: ['Carbondale', 'Honesdale', 'Dallas', 'Mountain Top', 'Back Mountain', 'Moscow', 'Tobyhanna', 'Blakely', 'Archbald', 'Jessup', 'Olyphant', 'Throop', 'Lake Ariel', 'Hamlin', 'Hawley', 'Milford'],
      faqs: [
        { q: 'How far does your service area extend?', a: 'We cover Lackawanna, Luzerne, Monroe, Wayne, and Pike counties. If you\'re unsure whether we serve your specific area, give us a call and we\'ll confirm.' },
        { q: 'Is there an extra charge for rural locations?', a: 'We do not charge trip fees within our standard service area. For locations at the outer edges, we\'ll let you know upfront if any travel charges apply.' },
      ],
    },
  ],

  serviceAreas: [
    'Scranton', 'Wilkes-Barre', 'Hazleton', 'Stroudsburg',
    'Pocono Mountains', 'Back Mountain', 'Pittston', 'Clarks Summit',
    'Dunmore', 'Old Forge', 'Moosic', 'Dallas',
    'Kingston', 'Nanticoke', 'Mountain Top', 'Dickson City',
    'Archbald', 'Carbondale', 'Honesdale', 'Milford',
    'East Stroudsburg', 'Tobyhanna', 'Mount Pocono', 'Hawley',
    'Lake Ariel', 'Hamlin', 'Moscow', 'Blakely',
    'Taylor', 'Throop', 'Jessup', 'Olyphant',
    'Allentown', 'Bethlehem', 'Easton',
  ],

  trustBadges: [
    { icon: 'shield', title: 'Licensed & Insured', text: 'Fully licensed plumbing contractor with comprehensive insurance coverage for your protection.' },
    { icon: 'clock', title: '24/7 Emergency Service', text: 'Plumbing emergencies don\'t wait. Our team is available around the clock for urgent issues.' },
    { icon: 'star', title: '5-Star Rated', text: 'Consistently rated 5 stars by homeowners and businesses across Northeastern PA.' },
    { icon: 'dollar', title: 'Upfront Pricing', text: 'No hidden fees or surprise charges. Transparent flat-rate pricing before any work begins.' },
  ],

  testimonials: [
    { name: 'Sarah M.', location: 'Scranton, PA', text: 'PrimeFlow replaced our old water heater in just a few hours. The technician was professional, explained everything, and left our basement cleaner than he found it. Highly recommend!', rating: 5, service: 'Water Heater Installation' },
    { name: 'James T.', location: 'Wilkes-Barre, PA', text: 'Called at 11pm with a burst pipe in our basement. PrimeFlow had someone at our door within 45 minutes. They stopped the flooding and had it fully repaired by morning. Lifesavers!', rating: 5, service: 'Emergency Plumbing' },
    { name: 'Linda K.', location: 'Pittston, PA', text: 'Best drain cleaning service I\'ve ever used. They used a camera to show me exactly what was causing the problem and cleared it completely. Fair price and great communication.', rating: 5, service: 'Drain Cleaning' },
    { name: 'Mike R.', location: 'Hazleton, PA', text: 'Had PrimeFlow replumb our entire 1920s home. The crew was respectful, efficient, and the quality of work was outstanding. Our water pressure is incredible now.', rating: 5, service: 'Whole Home Repiping' },
    { name: 'Jennifer D.', location: 'East Stroudsburg, PA', text: 'They winterized our Pocono vacation home and installed a new sump pump with battery backup. Very thorough and professional. We feel much better about our property.', rating: 5, service: 'Sump Pump Installation' },
    { name: 'Robert S.', location: 'Allentown, PA', text: 'PrimeFlow installed a tankless water heater and whole-home water filtration system. The difference in our water quality is remarkable. Professional crew, clean install.', rating: 5, service: 'Tankless Water Heater' },
    { name: 'Karen L.', location: 'Scranton, PA', text: 'Used PrimeFlow for our kitchen remodel plumbing. They coordinated perfectly with our contractor and the new farmhouse sink and faucet look amazing. No leaks, no issues.', rating: 5, service: 'Kitchen Plumbing' },
    { name: 'David W.', location: 'Wilkes-Barre, PA', text: 'Our sewer line had a major root intrusion. PrimeFlow used hydro jetting and showed me the before and after camera footage. Incredible difference. Fair pricing too.', rating: 5, service: 'Hydro Jetting' },
    { name: 'Angela P.', location: 'Clarks Summit, PA', text: 'Had multiple plumbers quote us for a gas line installation. PrimeFlow was the most thorough in their assessment and most reasonable on price. Excellent experience from start to finish.', rating: 5, service: 'Gas Line Services' },
  ],

  coupons: [
    { title: '$50 Off', subtitle: 'Any Service Over $300', code: 'PRIME50', description: 'Save $50 on any plumbing service totaling $300 or more. Cannot be combined with other offers.', expiry: 'Limited time offer' },
    { title: '$75 Off', subtitle: 'Water Heater Installation', code: 'HOTWATER75', description: 'Save $75 on any new water heater installation. Includes tank and tankless models.', expiry: 'Limited time offer' },
    { title: 'Free', subtitle: 'Drain Camera Inspection', description: 'Free sewer camera inspection with any drain cleaning service. See exactly what\'s happening in your pipes.', code: 'CAMERA2024', expiry: 'While available' },
    { title: '10% Off', subtitle: 'Senior & Military Discount', description: 'We proudly offer 10% off all services for seniors (65+) and active/retired military. Thank you for your service.', code: 'THANKYOU10', expiry: 'Always available' },
  ],

  generalFaqs: [
    { q: 'What areas do you serve?', a: 'PrimeFlow Plumbing serves all of Northeastern Pennsylvania including Scranton, Wilkes-Barre, Pittston, Hazleton, East Stroudsburg, Allentown, and dozens of surrounding communities across Lackawanna, Luzerne, Monroe, Wayne, and Pike counties.' },
    { q: 'Are you licensed and insured?', a: 'Yes, PrimeFlow Plumbing is fully licensed and insured with comprehensive general liability and workers\' compensation coverage. Your property and our team are always protected.' },
    { q: 'Do you offer free estimates?', a: 'Yes, we provide free estimates for most plumbing services. For diagnostic services like leak detection, there may be a service fee that is credited toward the repair if you choose us.' },
    { q: 'What are your business hours?', a: 'Our regular hours are Monday through Friday 7AM-6PM and Saturday 8AM-2PM. We offer 24/7 emergency plumbing service for urgent issues at any time.' },
    { q: 'Do you offer financing?', a: 'Yes, we offer flexible financing options for larger plumbing projects. Ask about our financing plans when you receive your estimate.' },
    { q: 'How quickly can you respond to an emergency?', a: 'We aim for a 60-minute response time for plumbing emergencies within our service area. Call our 24/7 emergency line and we\'ll dispatch a technician immediately.' },
    { q: 'Do you guarantee your work?', a: 'Absolutely. All PrimeFlow plumbing work comes with a satisfaction guarantee and written workmanship warranty. We stand behind everything we do.' },
    { q: 'Can I schedule a specific time for my appointment?', a: 'We offer convenient scheduling with 2-hour arrival windows. We also call ahead when our technician is on the way so you\'re not waiting around all day.' },
    { q: 'Do you clean up after the job?', a: 'Always. Our technicians wear shoe covers, use drop cloths, and leave your home as clean as they found it. It\'s part of the PrimeFlow standard.' },
    { q: 'What payment methods do you accept?', a: 'We accept cash, check, all major credit cards, and financing for qualifying projects. Payment is due upon completion of the work.' },
  ],

  seo: {
    siteUrl: 'https://www.primeflowplumbing.com',
    ogImage: '/images/og-image.jpg',
  },
};
