[build]
  command = "npm run build"
  publish = "."

[[redirects]]
  from = "/blog/:slug"
  to = "/blog/post.html?slug=:slug"
  status = 200

[[redirects]]
  from = "/services/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/service-areas/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
